### ISSUE TITLE
 lots of questions with the first sentence having no ending punctuation.

### ISSUE THREAD

**Issue by withchencheng** [vnik18/OPINE#3]
Another issue: there are lots of questions with the first sentence having no ending punctuation.
I suspect you just concat the question title and question content without checking where the question title has a correct ending punctuation.

For example, the first two lines:
```
In which epoch should i stop the training to avoid overfitting I'm working on an age estimation project trying to classify a given face in a predefined age range........

Deep learning with Tensorflow training with big data sets GoalI am trying to build a neural network that recognizes multiple label within a given image........(this one looks bad)
```

**Comment by vnik18** [comment]
Yes, that is right. We took this data from Stack Exchange, and did not need this information in our paper. So we did not use it.
